### ISSUE TITLE
Crash when inspecting FSM with Classes from assembly-csharp in it (Unity 2020.2)

### ISSUE THREAD

**Issue by SFGrenade** [nesrak1/FSMViewAvalonia#2]
FsmViewAvalonia just closes when looking at the `damages_enemy` fsm on the `Great Slash` gameobject in `scene4` of hollow knights 1.5 (i forgot the number) release

**Comment by nesrak1** [comment]
Couldn't reprod but try the latest update to see if it works now

**Comment by SFGrenade** [comment]
works now
