### ISSUE TITLE
[GOG, HK 1.5.68.11808] Hollow Knight data path assumed incorrectly

### ISSUE THREAD

**Issue by SFGrenade** [nesrak1/FSMViewAvalonia#4]
at `MainWindow.axaml.cs#L128` the path `hollow_knight_Data` is used, but with the 1.5.68.11808 release on GOG, Team Cherry decided to rename Hollow Knight internally from `hollow_knight` to `Hollow Knight`, with which the path `Hollow Knight_Data` would be the correct one.
Possible solution:
1. Check if `Hollow Knight_Data` folder exists
2. If it does, use that
3. If not, use `hollow_knight_Data`

**Comment by nesrak1** [comment]
I think even mac uses another path as well. Might be easier to just direct the user to the _data path.

**Comment by nesrak1** [comment]
Let me know if it works on gog now

**Comment by SFGrenade** [comment]
With Beta Release 4:
It searches in `E:\GOG\Hollow Knight 1432 Vanilla\hollow_knight_Data` wether or not there is a `hkpath.txt` existing, even if in it is a different path (e.g. `E:\GOG\Hollow Knight 1.5 Vanilla`) (it doesn't even try my steam install, which is amazing).

**Comment by SFGrenade** [comment]
closing it, File -> open is apparently windows' fault showing some other folder
